name: Build

on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
          gradle-version: 8.9
      - uses: BrycensRanch/read-properties-action@v1
        id: version
        with:
          file: gradle.properties
          property: mod_version
      - name: mc-publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: H1sntfo8
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 360203
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GIT_TOKEN }}
          files-primary: build/libs/!(*-@(javadoc|sources)).jar
          version-type: release
          loaders: neoforge
          game-versions: 1.21.1
          version: ${{ steps.version.outputs.value }}
          java: 21
          name: ""
          changelog-file: changelog-1.21.*
